# This rule is not used by the project actions-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over operator.actions-operator.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: actions-operator
    app.kubernetes.io/managed-by: kustomize
  name: actionsoperator-admin-role
rules:
- apiGroups:
  - operator.actions-operator.io
  resources:
  - actionsoperators
  verbs:
  - '*'
- apiGroups:
  - operator.actions-operator.io
  resources:
  - actionsoperators/status
  verbs:
  - get
